# Generated by Django 4.1.5 on 2023-04-12 18:45

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='piece',
            field=models.CharField(choices=[('4 piece', '4 piece'), ('5 piece', '5 piece'), ('1 piece', '1 piece'), ('2 piece', '2 piece'), ('3 piece', '3 piece'), ('6 piece', '6 piece')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='sanitaire',
            field=models.CharField(choices=[('Cuisine, salle de bain(wc)', 'Cuisine, salle de bain(wc)'), ('Cuisine, salle de bain, (wc) à part', 'Cuisine, salle de bain, (wc) à part'), ('Cuisine américaine, salle de bain (wc)', 'Cuisine américaine, salle de bain (wc)'), ('Cuisine américaine, salle de bain, (wc) à part', 'Cuisine américaine, salle de bain, (wc) à part')], max_length=100),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[250, 350], upload_to='photo'),
        ),
    ]
