# Generated by Django 4.1.5 on 2023-04-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_appartement_piece_alter_appartement_sanitaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='piece',
            field=models.CharField(choices=[('5 piece', '5 piece'), ('4 piece', '4 piece'), ('6 piece', '6 piece'), ('2 piece', '2 piece'), ('3 piece', '3 piece'), ('1 piece', '1 piece')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='sanitaire',
            field=models.CharField(choices=[('Cuisine, salle de bain(wc)', 'Cuisine, salle de bain(wc)'), ('Cuisine américaine, salle de bain, (wc) à part', 'Cuisine américaine, salle de bain, (wc) à part'), ('Cuisine, salle de bain, (wc) à part', 'Cuisine, salle de bain, (wc) à part'), ('Cuisine américaine, salle de bain (wc)', 'Cuisine américaine, salle de bain (wc)')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Annonce',
        ),
    ]
